s-sergiu/draw map (#3)
* Implemented read map function that returns a string;
Protected everything;

* Added libft and libft makefile;
Added draw map utils;

* Implemented read map height, width and area function;

* fixed double free

* Implemented draw map function which draws a blank screen with a small white image inside;

* added data structure

* Modified draw map function and utils to use the new map_data structure;
Added rectangle.cub map;

* cleaned up code

* Added comments above functions;

* Changed layout in accordance to the pitchfork layout.
Modified makefile temporarily to affect the changes.
Changed the location of MLX42 from libs to external folder.

* removed include/libft.h

* cleanup

* Cleaned up files, moved MLX from libs to external dir;

* added ft_putstring_fd

* Implemented error handling with correct exit codes and two custom
codes (empty map and bad file name);

* Added macos and ubuntu workflow actions;

* update makefile and github workflow (added valgrind memory check test)

* Implemented Doxygen documentation.
Modified header files with doxygen compatible comment explanations.

* updated docs

* modified location of GLFW for 42MACS

* Implemented not-so-tidy map drawing in draw_map.c.
Map has a simple grid with darkened walls, player is also spawning at (0,0)
with no collision detection.

* Removed player function from draw walls loop.
Function kept added infinite amount of players.

* Fixed norminette

* Reverted back to single include header and no subdirectories in src.

* Removed map utils subdir.

* updated docs

* Removed examples, tests, tools from Makefile make directory;
Placed filename_is_valid function in error_handling.c;
Updated docs: removed all MLX42 documentation.

* Removed filename_is_valid function (redundant).

* Updated docs.

* added 2 more valgrind checks to github actions

* Removed filename_is_valid check in main.

* Changed variable names in main and read_map.c (improved readability).

* Fixed norminette for include/cub3D.h

* Changed variable name.

* Added filename_is_valid function back.

* Fixed issue with dereferencing NULL pointer when accessing image
variable in main.c and when accessing data->map_string in init_map_data.

* Changed variable names (improved readability)

* implemented is a directory error check

* updated docs

* fixed function names for readability

* removed single lined print_error function

* updated docs

* improved makefile

* Added libft as a library to libs directory.

* improved makefile

* improved makefile

* added 1 test to ubuntu workflow

* fixed indentation for yml syntax error

* updated variable names - added extra meaning

* Added position struct, player data struct and game data struct;

* Implemented wall collision for player.

* Removed NULL assigment to player position when initializing it.
Fixed (error: incompatible types when assigning to type ‘struct s_position’
from type ‘void *’).

* Implemented player position.

* Added CMakeLists for libft and main project.
Implemented simple google test unit test in tests dir.

* Made separate CMakelist for tests dir;
Fixed test paths;

* Modified CMakeLists so that it enables testing on CMAKE_BUILD_TYPE=TEST parameter
passed at build.

* updated docs

* updated CMakeLists

* fixed makefile - added include dirs for MLX42 and libft

* changed include paths for mlx42 and libft

* updated include header statement

* updated CMakeLists

* included libft directory for TEST mode

* Added 2 maps for testing.
Added extra tests.

* update cmakelists minimum required version 3.10

---------

Co-authored-by: Djallal Mekki <djmekki@2-I-1.42heilbronn.de>